logging:
  level:
    org.springframework: ERROR
    com.sinaure: DEBUG

spring:
  profiles:
    active: dev
  
email: sinaure@gmail.com
repository: github/sinaure          
---

spring:
  profiles: dev
  datasource: 
    url: jdbc:postgresql://192.168.99.100:5432/sophia
    username: Jpasdetemps
    password: 65k
    initialize: true
  jpa:
    hibernate.ddl-auto: create 
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp: 
          use_jdbc_metadata_defaults: false

---

spring:
  profiles: prod
  datasource: 
    url: jdbc:postgresql://sophia-pg:5432/sophia
    username: Jpasdetemps
    password: 65k
    initialize: true
  jpa:
    hibernate.ddl-auto: update 
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp: 
          use_jdbc_metadata_defaults: false
      



wordpress:
  menus:
    - title: Home
      name: Home
      path: /
    - title: About
      name: About
      path: /about
  themes:
    default-folder: /wp-content/themes/mkyong
  servers:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3